### ISSUE TITLE
epoch rejection fails using epochs.plot

### ISSUE THREAD

**Issue by drammock** [pyeparse/pyeparse#59]
When I use `my_epochs_object.plot(block=True)`, click on some subplots, then click "reject-quit", `my_epochs_object` still has the same number of events in it: the rejection is not happening.  I was reminded of this issue by mne-tools/mne-python#2909, though I'm not certain they're related... in my case `block=True` seems to correctly halt execution (regardless of whether I'm running this through a python interpreter in a bash terminal, or through spyder).  Can anyone confirm?  My pyeparse version is up to date with current master (e582cc8), but my matplotlib is a little old (1.3.1).

**Comment by Eric89GXL** [comment]
Hmm, the `block=True` makes it so the behavior should be different from the mne-python issue.

It should modify the object, but it doesn't for me either. In case anyone else wants to have a look, here's the minimal script I'm using (assuming there is some reasonable `fname` defined):
```
raw = Raw(fname)
raw.remove_blink_artifacts()
events = raw.find_events('SYNCTIME', 1)
event_dict, tmin, tmax = dict(foo=1), -0.5, 1.
epochs = Epochs(raw, events, event_dict, tmin, tmax)
print(len(epochs))
epochs.plot(block=True)
print(len(epochs))
```
The culprit is [here] (https://github.com/pyeparse/pyeparse/blob/master/pyeparse/viz.py#L290). Can you try putting this in place of the conditional (no need for the conditional since it starts out as an empty list anyway)? It works for me.
```
p['epochs'].drop_epochs(p['reject_idx'])
```
You have time to make a PR?

**Comment by drammock** [comment]
tested, your fix works @Eric89GXL. PR #60.
